FROM debian:{{debian_release}}

{% for source_line in source_lines %}RUN echo '{{source_line}}' >> /etc/apt/sources.list.d/snapshot.list
{% endfor %}

RUN apt update
RUN apt install -y --allow-unauthenticated --allow-downgrades --fix-missing {{package_name}}

ARG USERNAME=toto
ARG PASSWORD=toto
RUN useradd -m ${USERNAME} -s /bin/bash && printf "${PASSWORD}\n${PASSWORD}\n" | passwd ${USERNAME} 2> /dev/null

{% if run_lines %}{% for line in run_lines %}RUN {{line}}
{% endfor %}{% endif %}
{% if cmd_line %}CMD {{cmd_line}}
{% endif %}
